# Generated by Django 4.2.7 on 2025-07-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='major',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='year_of_admission',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_phone',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='class_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
