# Generated by Django 4.2.7 on 2025-07-29 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=30)),
                ('building', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#4171c9', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Thứ 2'), (2, 'Thứ 3'), (3, 'Thứ 4'), (4, 'Thứ 5'), (5, 'Thứ 6'), (6, 'Thứ 7'), (7, 'Chủ nhật')])),
                ('start_period', models.IntegerField(choices=[(1, 'Tiết 1 (07:00-07:45)'), (2, 'Tiết 2 (07:50-08:35)'), (3, 'Tiết 3 (08:40-09:25)'), (4, 'Tiết 4 (09:35-10:20)'), (5, 'Tiết 5 (10:25-11:10)'), (6, 'Tiết 6 (13:00-13:45)'), (7, 'Tiết 7 (13:50-14:35)'), (8, 'Tiết 8 (14:40-15:25)'), (9, 'Tiết 9 (15:35-16:20)'), (10, 'Tiết 10 (16:25-17:10)')])),
                ('end_period', models.IntegerField(choices=[(1, 'Tiết 1 (07:00-07:45)'), (2, 'Tiết 2 (07:50-08:35)'), (3, 'Tiết 3 (08:40-09:25)'), (4, 'Tiết 4 (09:35-10:20)'), (5, 'Tiết 5 (10:25-11:10)'), (6, 'Tiết 6 (13:00-13:45)'), (7, 'Tiết 7 (13:50-14:35)'), (8, 'Tiết 8 (14:40-15:25)'), (9, 'Tiết 9 (15:35-16:20)'), (10, 'Tiết 10 (16:25-17:10)')])),
                ('teacher', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subject', 'weekday', 'start_period')},
            },
        ),
    ]
