# Generated by Django 4.2.7 on 2025-08-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='room',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scheduletemplate',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='ScheduleTemplate',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
