# Generated by Django 4.2.7 on 2025-08-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schedule', '0002_alter_schedule_unique_together_remove_schedule_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('scheduleID', models.CharField(max_length=8, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subjectID', models.CharField(max_length=8, unique=True)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('teacher', models.CharField(blank=True, max_length=100)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Schedule.schedule')),
            ],
        ),
    ]
