# Generated by Django 4.2.7 on 2025-08-09 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Schedule', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subjectID',
            new_name='subject_code',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#000', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='end_period',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='subject',
            name='start_period',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='weekday',
            field=models.IntegerField(default=1),
        ),
    ]
