# Generated by Django 4.2.7 on 2025-08-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0004_rename_subjectid_subject_subject_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='scheduleID',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
