# Generated by Django 4.2.7 on 2025-08-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0005_alter_schedule_scheduleid_alter_subject_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=32),
        ),
    ]
