# Generated by Django 4.2.7 on 2025-08-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0006_alter_subject_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(default='None', max_length=32, unique=True),
        ),
    ]
