# Generated by Django 4.2.7 on 2025-08-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0007_subject_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
